data:
    dataset: "ImageNet"
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 32
    subset_1k: True
    out_of_dist: False

training:
    batch_siz: 64
    microbatch_size: -1
    lr: 1e-4
    ema_rate: "0.9999",  # comma-separated list of EMA values
    log_interval: 10
    save_interval: 100
    resume_checkpoint: ""
    use_fp16: False
    fp16_scale_growth: 1e-3
    schedule_sampler: "uniform"
    weight_decay: 0.0
    lr_anneal_steps: 0


model:
    type: "openai"
    in_channels: 3
    out_channels: 3
    num_channels: 256
    num_heads: 4
    num_res_blocks: 2
    attention_resolutions: "32,16,8"
    dropout: 0.0
    resamp_with_conv: True
    learn_sigma: True
    use_scale_shift_norm: true
    use_fp16: true
    resblock_updown: true
    num_heads_upsample: -1
    var_type: 'fixedsmall'
    num_head_channels: 64
    image_size: 256
    class_cond: false
    use_new_attention_order: false

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 1
    
time_travel:
    T_sampling: 100
    travel_length: 10
    travel_repeat: 3